var DIRECTORY = [
  {
    "id":"1000",
    "name":"Osaka Supermarket",
    "type":"Supermarket",
    "category":"Food & Grocery",
    "phone":"604-276-8808",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"1035",
    "name":"Wah Yuen",
    "type":"Food",
    "category":"Food & Grocery",
    "phone":"604-231-9080",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"1040",
    "name":"Chun Hing",
    "type":"Food",
    "category":"Food & Grocery",
    "phone":"604-278-3055",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"1045",
    "name":"Golden Rice Bowl",
    "type":"Food",
    "category":"Food & Grocery",
    "phone":"604-244-8082",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"1050",
    "name":"Pak Tak",
    "type":"Food",
    "category":"Food & Grocery",
    "phone":"604-231-9096",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"1055",
    "name":"Little Bean Tea Station",
    "type":"Food",
    "category":"Food & Grocery",
    "phone":"604-278-7113",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"1060",
    "name":"Juice King",
    "type":"Food",
    "category":"Food & Grocery",
    "phone":"778-883-9669",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"1065",
    "name":"Fok Po Tong",
    "type":"Food",
    "category":"Food & Grocery",
    "phone":"604-278-3345",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"1070",
    "name":"Curry House",
    "type":"Food",
    "category":"Food & Grocery",
    "phone":"604-721-2426",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"1075",
    "name":"Sun Century",
    "type":"Food",
    "category":"Food & Grocery",
    "phone":"604-278-0838",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"1080",
    "name":"Ajea Noodles",
    "type":"Food",
    "category":"Food & Grocery",
    "phone":"236-889-2036",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"1085",
    "name":"Countryside Noodles",
    "type":"Food",
    "category":"Food & Grocery",
    "phone":"604-773-3032",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"1090",
    "name":"Datang BBQ Express",
    "type":"Food",
    "category":"Food & Grocery",
    "phone":"604-231-9673",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"1095",
    "name":"Seoul Express",
    "type":"Food",
    "category":"Food & Grocery",
    "phone":"604-821-1775",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"1100",
    "name":"Lumingchun",
    "type":"Food",
    "category":"Food & Grocery",
    "phone":"604-821-0828",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"1105",
    "name":"Fresh Elements Bubble Tea and Juice",
    "type":"Food",
    "category":"Food & Grocery",
    "phone":"604-284-5382",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2120",
    "name":"Mapleville",
    "type":"Candies and Snacks",
    "category":"Food & Grocery",
    "phone":"778-822-6522",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2025",
    "name":"Senda Salon",
    "type":"Hair Salon/ Product",
    "category":"Health & Beauty",
    "phone":"604-278-1221",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2135",
    "name":"Longevita Nutrition",
    "type":"Health Food",
    "category":"Health & Beauty",
    "phone":"604-207-9900",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2215",
    "name":"Sung's Salon",
    "type":"Hair Salon",
    "category":"Health & Beauty",
    "phone":"604-231-9699",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2235",
    "name":"Xue Jun Chinese Medicine and Acupuncture",
    "type":"Chinese Medicine and Acupuncture",
    "category":"Health & Beauty",
    "phone":"604-273-0001",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2260",
    "name":"Park Pacific Pharmacy",
    "type":"Pharmacy",
    "category":"Health & Beauty",
    "phone":"604-273-9812",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2265",
    "name":"Dentist Paul Wong",
    "type":"Dental Clinic",
    "category":"Health & Beauty",
    "phone":"604-231-9888",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2270",
    "name":"Dr. James Hung",
    "type":"Medical Clinic",
    "category":"Health & Beauty",
    "phone":"604-273-0990",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2440",
    "name":"G-Way",
    "type":"Health Food",
    "category":"Health & Beauty",
    "phone":"604-270-4929",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2550",
    "name":"F10 Quick Cut",
    "type":"Hair Salon",
    "category":"Health & Beauty",
    "phone":"",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2100",
    "name":"All for Women",
    "type":"Fashion",
    "category":"Clothing & Accessory",
    "phone":"604-277-7758",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2220",
    "name":"Pinky Fashion",
    "type":"Fashion",
    "category":"Clothing & Accessory",
    "phone":"604-278-1308",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2225",
    "name":"Yobo",
    "type":"Clothing",
    "category":"Clothing & Accessory",
    "phone":"604-273-0863",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2310",
    "name":"Fashion Square",
    "type":"Fashion",
    "category":"Clothing & Accessory",
    "phone":"604-273-1383",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2325",
    "name":"Way Chuan",
    "type":"Fashion",
    "category":"Clothing & Accessory",
    "phone":"604-278-3189",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2425",
    "name":"Byworld",
    "type":"Fashion",
    "category":"Clothing & Accessory",
    "phone":"604-232-0328",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2020",
    "name":"Perfect Frame Aesthetic Gallery",
    "type":"Painting and Framing",
    "category":"Art & Craft",
    "phone":"604-821-0890",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2105",
    "name":"Chanty Art Link",
    "type":"Painting",
    "category":"Art & Craft",
    "phone":"604-231-8139",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2110",
    "name":"2-12 Arts & Crafts",
    "type":"Art and Craft",
    "category":"Art & Craft",
    "phone":"604-231-8112",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2450/55",
    "name":"Chinese Painting",
    "type":"Paintings & Art",
    "category":"Art & Craft",
    "phone":"604-276-1818",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"1020",
    "name":"Harmony Books & Video",
    "type":"Book's & Magazines",
    "category":"Gift & Hobby",
    "phone":"604-278-1668",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2030",
    "name":"Fukui Gift Shop",
    "type":"Gifts",
    "category":"Gift & Hobby",
    "phone":"604-232-0888",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2035",
    "name":"Multimedia Game Boutique",
    "type":"Electronic Games",
    "category":"Gift & Hobby",
    "phone":"604-279-0851",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2230",
    "name":"Red Sen",
    "type":"Health Food",
    "category":"Gift & Hobby",
    "phone":"778-882-7383",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"1005",
    "name":"Dream Vacation Architect Inc.",
    "type":"Travel Agency",
    "category":"Specialty & Service",
    "phone":"604-370-3038",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"1010",
    "name":"Apex Insurance",
    "type":"Insurance Agency",
    "category":"Specialty & Service",
    "phone":"604-273-1668",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"1015",
    "name":"Wing Shing",
    "type":"Herbal Medicine",
    "category":"Specialty & Service",
    "phone":"604-278-1117",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"1025",
    "name":"Kingmark Canada Currency Exchange Inc.",
    "type":"Money Exchange",
    "category":"Specialty & Service",
    "phone":"604-273-8100",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"1030",
    "name":"Time College Group",
    "type":"Education",
    "category":"Specialty & Service",
    "phone":"778-895-2938",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2005",
    "name":"Fukunoya",
    "type":"Houseware",
    "category":"Specialty & Service",
    "phone":"604-231-8001",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2010",
    "name":"Fukunoya",
    "type":"Houseware",
    "category":"Specialty & Service",
    "phone":"604-231-8001",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2015",
    "name":"Bodylax",
    "type":"Massage Chair",
    "category":"Specialty & Service",
    "phone":"604-808-3268",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2040",
    "name":"Golden Jade House",
    "type":"Fung Shui",
    "category":"Specialty & Service",
    "phone":"604-303-6578",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2045",
    "name":"Sea & Sky Travel",
    "type":"Travel Agency",
    "category":"Specialty & Service",
    "phone":"604-288-0309",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2050",
    "name":"President Global/Grand Maple",
    "type":"Immigration and Education Consultant",
    "category":"Specialty & Service",
    "phone":"604-370-2855",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2055",
    "name":"PG Homes",
    "type":"Realty",
    "category":"Specialty & Service",
    "phone":"604-370-2855",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2060",
    "name":"JT Travel",
    "type":"Travel Agency",
    "category":"Specialty & Service",
    "phone":"604-285-8685",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2115",
    "name":"Clarify",
    "type":"Water Purifier",
    "category":"Specialty & Service",
    "phone":"604-278-9597",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2125",
    "name":"Mainland Travel",
    "type":"Travel Agency",
    "category":"Specialty & Service",
    "phone":"604-658-8877",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2130",
    "name":"President Global/Grand Maple",
    "type":"Immigration and Education Consultant",
    "category":"Specialty & Service",
    "phone":"604-370-2855",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2205",
    "name":"Gibo Health Food Ltd.",
    "type":"Chinese Herbs",
    "category":"Specialty & Service",
    "phone":"604-304-2958",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2210",
    "name":"Coinmarket",
    "type":"Currency Exchange",
    "category":"Specialty & Service",
    "phone":"604-767-1022",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2245",
    "name":"Little Ants",
    "type":"Interactive Learning",
    "category":"Specialty & Service",
    "phone":"",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2255",
    "name":"Bayshore Business Centre",
    "type":"Consulting Service",
    "category":"Specialty & Service",
    "phone":"604-270-1123",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2275",
    "name":"Regent Park",
    "type":"Realty",
    "category":"Specialty & Service",
    "phone":"604-606-8188",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2300/05",
    "name":"A Fontane Beddings",
    "type":"Pillows & Beddings",
    "category":"Specialty & Service",
    "phone":"604-231-8000",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2315",
    "name":"Blynx Optical",
    "type":"Fashion Eyewear",
    "category":"Specialty & Service",
    "phone":"604-304-2759",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2320",
    "name":"Yaohan Optical",
    "type":"Eye Care Centre",
    "category":"Specialty & Service",
    "phone":"604-270-1618",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2330",
    "name":"Zhlshop Appliances",
    "type":"Home Appliances",
    "category":"Specialty & Service",
    "phone":"778-320-9158",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2340",
    "name":"Susanna Wedding",
    "type":"Wedding Services",
    "category":"Specialty & Service",
    "phone":"604-278-8987",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2345",
    "name":"Jin Hong International",
    "type":"Immigration",
    "category":"Specialty & Service",
    "phone":"604-998-8238",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2350",
    "name":"Oasis Water Filtration",
    "type":"Water Filtration",
    "category":"Specialty & Service",
    "phone":"604-270-1885",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2400",
    "name":"iTalkBB",
    "type":"Cell Phone",
    "category":"Specialty & Service",
    "phone":"604-998-6666",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2405",
    "name":"El's Gem Stone",
    "type":"Semi-precious Stone",
    "category":"Specialty & Service",
    "phone":"604-781-8800",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2410",
    "name":"Canvision Travel",
    "type":"Travel Agency",
    "category":"Specialty & Service",
    "phone":"604-370-7086",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2415",
    "name":"Jiu Xin Financial",
    "type":"Currency transfer",
    "category":"Specialty & Service",
    "phone":"604-303-6563",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2420",
    "name":"GEG Travel",
    "type":"Travel Agency",
    "category":"Specialty & Service",
    "phone":"604-370-3337",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2430",
    "name":"ICI Computer",
    "type":"Computer Service",
    "category":"Specialty & Service",
    "phone":"604-273-1368",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2500",
    "name":"J & A Ginseng",
    "type":"Ginseng",
    "category":"Specialty & Service",
    "phone":"604-304-1870",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2505",
    "name":"J & A Ginseng",
    "type":"Ginseng",
    "category":"Specialty & Service",
    "phone":"604-304-1870",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2510",
    "name":"Revel in Years",
    "type":"Tea",
    "category":"Specialty & Service",
    "phone":"778-322-7977",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2515",
    "name":"Chun Yen Liu Notary Public",
    "type":"Notary Public",
    "category":"Specialty & Service",
    "phone":"778-997-7568",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2525",
    "name":"Chun Yen Liu Notary Public",
    "type":"Notary Public",
    "category":"Specialty & Service",
    "phone":"778-997-7568",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2535",
    "name":"Rioshine Tax & Accounting",
    "type":"Tax and Accounting Services",
    "category":"Specialty & Service",
    "phone":"604-370-3958",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  },
  {
    "id":"2560",
    "name":"Rioshine Commercial Properties",
    "type":"Consulting Service",
    "category":"Specialty & Service",
    "phone":"604-285-1898",
    "email":"",
    "description":"",
    "xAxis":"",
    "yAxis":"",
    "image":""
  }];